### ISSUE TITLE
output vtu

### ISSUE THREAD

**Issue by rpshi** [ImperialCollegeLondon/pnextract#7]
Hi Ali,

Thanks again for the great tool.

I downloaded "Bentheimer sandstone" dataset by following the link below.

https://www.imperial.ac.uk/earth-science/research/research-groups/pore-scale-modelling/micro-ct-images-and-networks/

I was able to use the code to generate pore and throat network with corresponding vtu files. 

The vtu files for medial surface and mb hierarchy0 are 

Bentheimer_medialSurface0.vtu (1.1kb)
Bentheimer_mbHierarchy0.vtu. (1.1 kb)

I was able to load them using paraview and found out that the number of cells and points are 0.

Am i missing anything here.

Thanks,

R

Please see my input file below.

Bentheimer_1000c_3p0035um.mhd

ObjectType =  Image
NDims =	   3
ElementType = MET_UCHAR
ElementByteOrderMSB = False
ElementNumberOfChannels = 1
CompressedData = True

DimSize =        1000  1000  1000
ElementSpacing = 3.0035   3.0035   3.0035 
Offset =         0      0      0

ElementDataFile = Bentheimer_1000c_3p0035um.raw.gz

title Bentheimer;

write_radius = True
write_element = True
write_poreMaxBalls = True
write_throatMaxBall = True
write_throats = True
write_hierarchy = True
write_medialSurface = True
write_throatHierarchy = True
write_vtkNetwork = True
write_cnm = True

end

**Comment by aliraeini** [comment]
@rpshi ,  I think I should have mentioned my name like @raeini so that I get  notified about this message... sorry about the delay.

This often can be a result of the image not being read properly, I can't tell exactly what happened unless you send me the output log of pnextract code. which can be either copied from command-line outputs, or by redirecting the stdout and stderr to a file by running the code like:

`pnextract.exe > log.pnextract.txt 2>&1`





In case,

**Comment by rpshi** [comment]
OK, Thanks for your time and constant support!

**Comment by EdgarL0** [comment]
Hi,

I have the exact same problem on the same image "Bentheimer sandstone" and on an other sample I'm working on. Here are the according logs from pnextract :

[log_Bentheimer.txt](https://github.com/aliraeini/pnextract/files/6754206/log_Bentheimer.txt)
[log.txt](https://github.com/aliraeini/pnextract/files/6754207/log.txt)

It look's like everything is fine except from the medialSurface0 and mbHierarchy0 vtu files.

I hope this might help.

Thanks, 

Edgar.

**Comment by aliraeini** [comment]
Thanks Edgar and rpshi for taking the time and reporting this. 

Yes I checked and can confirm this was essentially a problem with pnextract.  I updated the code and removed the write_medialSurface, which required additional data from the generalized network version that are not missing and not needed in pnextract.  The problem with write_hierarchy should be fixed though.

Cheers, 
Ali
